# Generated by Django 3.0.3 on 2020-08-21 13:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(default='Novel', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
            ],
        ),
        migrations.CreateModel(
            name='DBBook',
            fields=[
                ('ISBN', models.CharField(default='123123', max_length=13, primary_key=True, serialize=False)),
                ('title', models.CharField(default=None, max_length=255, null=True)),
                ('author', models.CharField(default=None, max_length=255, null=True)),
                ('pub_date', models.IntegerField(default=None, null=True)),
                ('publisher', models.CharField(default=None, max_length=255, null=True)),
                ('img_url_s', models.URLField(default=None, null=True)),
                ('img_url_m', models.URLField(default=None, null=True)),
                ('img_url_l', models.URLField(default=None, null=True)),
                ('b_c', models.URLField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='DBUser',
            fields=[
                ('user_id', models.IntegerField(blank=True, default=0, primary_key=True, serialize=False)),
                ('location', models.CharField(default=None, max_length=250, null=True)),
                ('age', models.IntegerField(default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='UserAddedBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_added_book', to=settings.AUTH_USER_MODEL)),
                ('user_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rcsystem.DBBook')),
            ],
        ),
        migrations.CreateModel(
            name='BookComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('approved_comment', models.BooleanField(default=False)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_comment_book', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='rcsystem.DBBook')),
            ],
        ),
        migrations.CreateModel(
            name='DBBookRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ISBN', models.CharField(default='123123', max_length=13)),
                ('rating', models.IntegerField(default=0, null=True)),
                ('user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='rcsystem.DBUser')),
            ],
            options={
                'unique_together': {('user', 'ISBN')},
            },
        ),
    ]
