# Generated by Django 3.0.3 on 2020-08-21 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rcsystem', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dbbook',
            name='b_c',
        ),
    ]
