# Generated by Django 3.0.3 on 2020-08-21 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rcsystem', '0003_dbbook_book_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dbbook',
            name='book_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='book_category', to='rcsystem.BookCategory'),
        ),
    ]
