# Generated by Django 3.0.3 on 2020-08-21 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rcsystem', '0004_auto_20200821_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dbbook',
            name='book_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_category', to='rcsystem.BookCategory'),
        ),
    ]
