# Generated by Django 3.0.3 on 2020-08-21 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rcsystem', '0006_auto_20200821_1632'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BookComment',
        ),
    ]
