# Generated by Django 3.0.3 on 2020-08-21 13:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rcsystem', '0009_remove_bookcomment_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookcomment',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_comment_book', to=settings.AUTH_USER_MODEL),
        ),
    ]
