# Generated by Django 3.0.3 on 2020-08-21 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rcsystem', '0010_bookcomment_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dbbook',
            name='book_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_book', to='rcsystem.BookCategory'),
        ),
    ]
