# Generated by Django 3.0.3 on 2020-08-21 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rcsystem', '0012_auto_20200821_1650'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookcomment',
            name='post',
        ),
    ]
