# Generated by Django 3.0.3 on 2020-08-21 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rcsystem', '0013_remove_bookcomment_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookcomment',
            name='book',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='comments_book', to='rcsystem.DBBook'),
        ),
    ]
