# Generated by Django 3.0.3 on 2020-08-21 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rcsystem', '0014_bookcomment_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='dbbook',
            name='book_favorites_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dbbook',
            name='book_overall_favorite',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dbbook',
            name='book_user_favorite',
            field=models.IntegerField(choices=[(0, 'Not Rated'), (1, 'Poor'), (2, 'Average'), (3, 'Good'), (4, 'Very Good'), (5, 'Excellent')], default=0),
        ),
    ]
