# Generated by Django 3.0.3 on 2020-08-21 17:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rcsystem', '0016_auto_20200821_1755'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRatedBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_user_rated', models.IntegerField(choices=[(0, 'Not Rated'), (1, 'Poor'), (2, 'Average'), (3, 'Good'), (4, 'Very Good'), (5, 'Excellent')], default=0)),
                ('book', models.ForeignKey(max_length=13, on_delete=django.db.models.deletion.CASCADE, related_name='rated_book', to='rcsystem.DBBook')),
                ('user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rated_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'book')},
            },
        ),
    ]
