# Generated by Django 3.0.3 on 2020-08-21 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rcsystem', '0017_userratedbook'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userratedbook',
            old_name='book_user_rated',
            new_name='user_rated',
        ),
    ]
