# Generated by Django 3.0.3 on 2020-08-26 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rcsystem', '0018_auto_20200821_2057'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewBooks',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('book_id', models.IntegerField()),
                ('best_book_id', models.IntegerField()),
                ('work_id', models.IntegerField()),
                ('books_count', models.IntegerField()),
                ('isbn', models.CharField(max_length=250)),
                ('isbn13', models.CharField(max_length=250)),
                ('authors', models.CharField(max_length=250)),
                ('original_publication_year', models.CharField(max_length=250)),
                ('original_title', models.CharField(max_length=250)),
                ('title', models.CharField(max_length=250)),
                ('language_code', models.CharField(max_length=250)),
                ('average_rating', models.FloatField()),
                ('ratings_count', models.IntegerField()),
                ('work_ratings_count', models.IntegerField()),
                ('work_text_reviews_count', models.IntegerField()),
                ('ratings_1', models.IntegerField()),
                ('ratings_2', models.IntegerField()),
                ('ratings_3', models.IntegerField()),
                ('ratings_4', models.IntegerField()),
                ('ratings_5', models.IntegerField()),
                ('image_url', models.IntegerField()),
                ('small_image_url', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('categories', models.TextField()),
            ],
        ),
    ]
