# Generated by Django 3.0.3 on 2020-08-26 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rcsystem', '0019_newbooks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newbooks',
            name='image_url',
            field=models.CharField(max_length=250),
        ),
    ]
