# Generated by Django 3.0.3 on 2020-08-26 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rcsystem', '0020_auto_20200826_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newbooks',
            name='authors',
            field=models.TextField(),
        ),
    ]
