# Generated by Django 3.0.3 on 2020-08-27 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rcsystem', '0021_auto_20200826_1510'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewBooks',
        ),
    ]
