# Generated by Django 3.0.3 on 2020-08-27 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rcsystem', '0023_newbooks'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewBooksRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('rating', models.IntegerField()),
                ('book_id', models.ForeignKey(db_column='get_books', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='rcsystem.NewBooks', to_field='book_id')),
            ],
            options={
                'unique_together': {('book_id', 'user_id')},
            },
        ),
    ]
