# Generated by Django 3.0.3 on 2020-08-27 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rcsystem', '0024_newbooksrating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newbooksrating',
            name='book_id',
            field=models.ForeignKey(db_column='book_id', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='rcsystem.NewBooks', to_field='book_id'),
        ),
    ]
