# Generated by Django 3.0.3 on 2020-08-27 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rcsystem', '0025_auto_20200827_1328'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NewBooksRating',
            new_name='NewBooksRatings',
        ),
    ]
