# Generated by Django 3.0.3 on 2020-08-27 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rcsystem', '0027_auto_20200827_1459'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewBooks',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('book_id', models.IntegerField(unique=True)),
                ('best_book_id', models.IntegerField()),
                ('work_id', models.IntegerField()),
                ('books_count', models.IntegerField()),
                ('isbn', models.CharField(max_length=250)),
                ('isbn13', models.CharField(max_length=250)),
                ('authors', models.TextField()),
                ('original_publication_year', models.CharField(max_length=250)),
                ('original_title', models.CharField(max_length=250)),
                ('title', models.CharField(max_length=250)),
                ('language_code', models.CharField(max_length=250)),
                ('average_rating', models.FloatField()),
                ('ratings_count', models.IntegerField()),
                ('work_ratings_count', models.IntegerField()),
                ('work_text_reviews_count', models.IntegerField()),
                ('ratings_1', models.IntegerField()),
                ('ratings_2', models.IntegerField()),
                ('ratings_3', models.IntegerField()),
                ('ratings_4', models.IntegerField()),
                ('ratings_5', models.IntegerField()),
                ('image_url', models.CharField(max_length=250)),
                ('small_image_url', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('categories', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='NewBooksRatings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('rating', models.IntegerField()),
                ('book_id', models.ForeignKey(db_column='book_id', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='rcsystem.NewBooks', to_field='book_id')),
            ],
            options={
                'unique_together': {('book_id', 'user_id')},
            },
        ),
    ]
