# Generated by Django 3.0.3 on 2020-08-28 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rcsystem', '0028_newbooks_newbooksratings'),
    ]

    operations = [
        migrations.AddField(
            model_name='newbooks',
            name='clean_description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='newbooks',
            name='soup',
            field=models.TextField(default=''),
        ),
    ]
