# Generated by Django 3.0.3 on 2020-08-28 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rcsystem', '0030_auto_20200828_1311'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newbooksratings',
            old_name='book_id',
            new_name='book',
        ),
    ]
