# Generated by Django 3.0.3 on 2020-08-28 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rcsystem', '0031_auto_20200828_1311'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='newbooksratings',
            unique_together=set(),
        ),
    ]
