# Generated by Django 3.0.3 on 2020-08-31 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rcsystem', '0033_auto_20200828_1315'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieDatabase',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('imdb_id', models.CharField(max_length=250)),
                ('clean_imdb_id', models.IntegerField()),
                ('original_language', models.CharField(max_length=250)),
                ('original_title', models.CharField(max_length=250)),
                ('title', models.CharField(max_length=250)),
                ('overview', models.TextField()),
                ('genres', models.CharField(max_length=250)),
                ('cast', models.CharField(max_length=250)),
                ('director', models.CharField(max_length=250)),
                ('keywords', models.CharField(max_length=250)),
                ('spoken_languages', models.CharField(max_length=250)),
                ('production_countries', models.CharField(max_length=250)),
                ('production_companies', models.CharField(max_length=250)),
                ('popularity', models.FloatField()),
                ('release_date', models.CharField(max_length=250)),
                ('tagline', models.CharField(max_length=250)),
                ('vote_average', models.FloatField()),
                ('vote_count', models.IntegerField()),
                ('runtime', models.IntegerField()),
                ('poster', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='MovieRatings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('rating', models.IntegerField()),
                ('movie', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='rcsystem.MovieDatabase')),
            ],
            options={
                'unique_together': {('movie', 'user_id')},
            },
        ),
    ]
