# Generated by Django 3.0.3 on 2020-08-31 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rcsystem', '0034_moviedatabase_movieratings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moviedatabase',
            old_name='cast',
            new_name='casts',
        ),
    ]
