# Generated by Django 3.0.3 on 2020-08-31 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rcsystem', '0037_auto_20200831_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviedatabase',
            name='tagline',
            field=models.TextField(),
        ),
    ]
