# Generated by Django 3.0.3 on 2020-08-31 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rcsystem', '0039_auto_20200831_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviedatabase',
            name='vote_average',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='moviedatabase',
            name='vote_count',
            field=models.CharField(max_length=250),
        ),
    ]
