# Generated by Django 3.0.3 on 2020-09-01 11:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rcsystem', '0042_moviedatabase_movie_index'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movieratings',
            old_name='movie',
            new_name='movie_id',
        ),
        migrations.AddField(
            model_name='movieratings',
            name='timestamp',
            field=models.DateTimeField(default=None, verbose_name='rated at'),
        ),
        migrations.AlterField(
            model_name='movieratings',
            name='rating',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='movieratings',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='movieratings',
            unique_together={('user_id', 'movie_id')},
        ),
    ]
