# Generated by Django 3.0.3 on 2020-09-01 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rcsystem', '0043_auto_20200901_1435'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movieratings',
            old_name='movie_id',
            new_name='movie',
        ),
        migrations.RenameField(
            model_name='movieratings',
            old_name='user_id',
            new_name='user',
        ),
    ]
