# Generated by Django 3.0.3 on 2020-09-01 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rcsystem', '0045_auto_20200901_1635'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bookratings',
            unique_together=set(),
        ),
    ]
