# Generated by Django 3.0.3 on 2020-09-02 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rcsystem', '0046_auto_20200901_1641'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
