# Generated by Django 3.0.3 on 2020-09-02 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rcsystem', '0047_delete_post'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BookCategory',
            new_name='DBBookCategory',
        ),
    ]
