# Generated by Django 3.0.3 on 2020-09-02 14:15

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rcsystem', '0048_auto_20200902_1713'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserAddedBook',
            new_name='DBUserAddedBook',
        ),
    ]
