# Generated by Django 3.0.3 on 2020-09-02 14:16

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rcsystem', '0049_auto_20200902_1715'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BookComment',
            new_name='DBBookComment',
        ),
    ]
