# Generated by Django 3.0.3 on 2020-09-02 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rcsystem', '0051_auto_20200902_1717'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewBooksRatings',
        ),
    ]
