# Generated by Django 3.0.3 on 2020-09-02 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rcsystem', '0052_delete_newbooksratings'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NewBooks',
            new_name='BookDatabase',
        ),
    ]
