# Generated by Django 3.0.3 on 2020-09-03 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rcsystem', '0053_auto_20200902_1720'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='moviedatabase',
            options={'ordering': ['movie_index']},
        ),
    ]
